[versions]
kotlin_lang = "1.9.10"
kotlin_coroutines = "1.7.3"
androidx_core = "1.12.0"
androidx_compose_bom = "2023.10.01"
androidx_compose_compiler = "1.5.3"
androidx_lifecycle = "2.6.2"
androidx_savedstate = "1.2.1"
firebase_firestore = "24.0.1"
firebase_auth = "21.0.1"

[libraries]
android-gradle-plugin = "com.android.tools.build:gradle:8.1.2"
vespene = "net.mbonnin.vespene:vespene-lib:0.5"

kotlin_gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin_lang" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin_coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin_coroutines" }
kotlin-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlin_coroutines" }

firebase_firestore = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebase_firestore" }
firebase_auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebase_auth" }

androidx_core = { module = "androidx.core:core-ktx", version.ref = "androidx_core" }
androidx_savedstate = { module = "androidx.savedstate:savedstate-ktx", version.ref = "androidx_savedstate" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx_compose_bom" }
androidx_compose_material = { module = "androidx.compose.material:material" }
androidx_compose_material3 = { module = "androidx.compose.material3:material3" }
androidx_compose_ui = { module = "androidx.compose.ui:ui" }
androidx_compose_runtime = { module = "androidx.compose.runtime:runtime" }
androidx_compose_foundation = { module = "androidx.compose.foundation:foundation" }
androidx_compose_uitooling = { module = "androidx.compose.ui:ui-tooling" }
androidx_lifecycle_viewmodel_compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx_lifecycle" }
androidx_lifecycle_runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx_lifecycle" }
androidx_lifecycle_viewmodel_ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx_lifecycle" }
